### PR TITLE
[Android] Added PrinterPDF class

### PR DESCRIPTION
**Pull request by dimitriadamou**
- This only works for printing PDFs will not work on images.
- Only works with PDFs that have been downloaded 
- String path must begin with file:/// and end with .pdf

### CODE REVIEW

**Comment by katzer** [comment]
@dimitriadamou 

Thanks a lot for your PR. I would merge the PR if there're no conflicts anymore. I've integrated your code into the dev branch

**Comment by dimitriadamou** [comment]
I'll close PR thanks

**Comment by hieuntp2** [comment]
Hi @dimitriadamou , Could you have some demo how I can use this plugins to print PDF? I already download this file, and open success with file-opener plugin. The URL I store file to local: file:///data/user/0/io.ionic.Inspekt/files/file.pdf

Please help. 
Thank you

**Comment by dimitriadamou** [comment]
@hieuntp2 you should ignore this PR, download the latest 0.8 release, 

I'm unsure how it works with ionic as I have never used it - but the URI looks about right

```
   var file = 'file:///data/user/0/io.ionic.Inspekt/files/file.pdf';
   cordova.plugins.printer.print(file, { border: false, name: "file.pdf" });
```

**Comment by hieuntp2** [comment]
Thank you, I try to use version 0.8

**Pull request closed without merging**
