### PR TITLE
Replaced deprecated function reference

### PR DESCRIPTION
**Pull request by zakton5**
Replaced deprecated function reference that prevents ios apps from building.

### CODE REVIEW

**Comment by purid** [comment]
Worked for me

**Comment by unostella** [comment]
It does build with that #71 fix. Thanks

**Comment by EddieMachete** [comment]
This update worked for me too.  Will this ever make it into the master branch?  Right now I have to manually apply the change overtime my team needs a new build.  At least once every two weeks.

Thanks for the fix, tho.

**Comment by katzer** [comment]
See https://github.com/katzer/cordova-plugin-printer/commit/15b9b588b2d7ccba8461345c804a2acb4a1bb65b

**Pull request closed without merging**
